name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tarball (skip dotgit and node_modules)
        run: |
          tar -czf gamesdom.tar.gz \
            --exclude='.git' \
            --exclude='api/node_modules' \
            .

      - name: Upload tarball to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }} # e.g. ec2-user or ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "gamesdom.tar.gz"
          target: "/tmp/"

      - name: Run remote deploy script
        uses: appleboy/ssh-action@v1.2.0
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: GITHUB_SHA
          script: |
            export GITHUB_SHA="${GITHUB_SHA}"
            sudo mv /tmp/gamesdom.tar.gz /tmp/gamesdom.tar.gz
            sudo /opt/gamesdom/deploy/deploy.sh
