name: Deploy to EC2

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tarball (stable via git archive)
        run: |
          git archive --format=tar.gz -o gamesdom.tar.gz HEAD

      - name: Upload tarball to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }} # e.g. ec2-user or ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "gamesdom.tar.gz"
          target: "/tmp/"

      - name: Run remote deploy script
        uses: appleboy/ssh-action@v1.2.0
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: GITHUB_SHA
          script: |
            export GITHUB_SHA="${GITHUB_SHA}"
            ls -lh /tmp/gamesdom.tar.gz
            sudo --preserve-env=GITHUB_SHA /opt/gamesdom/deploy/deploy.sh
